// eslint-disable-next-line import/no-anonymous-default-export
export default {
    home:{
        title:"TODO APP",
        description:"自分だけのTODOを作成しよう！",
        buttonTitle1:"新規アカウント作成",
        buttonTitle2:"ログイン",
    },
    signup:{
        title:"新規登録",
        instruction:"名前、メールアドレス、パスワードを入力してください。",
        validationCheck:{
            required:"この項目は必須です",
            email:"メールアドレスの形式が違います",
            password:"パスワードが短いです"
        },
        attribute:{
            name:{
                labelName:"name",
            },
            email:{
                labelName:"email",
                typeName:"email",
            },
            password:{
                labelName:"password",
                typeName:"password",
            }
        },
        buttonTitle:"新規登録する",
        gobackBotton:"ホームに戻る",
        alradyHaveAccount:"データはもうすでにあります",
    },
    login:{
        title:"ログイン",
        instruction:"メールアドレスとパスワードを入れてください。",
        validationCheck:{
            required:"この項目は必須です",
            email:"メールアドレスの形式が違います",
            password:"パスワードが短いです"
        },
        attribute:{
            email:{
                labelName:"email",
                typeName:"email",
            },
            password:{
                labelName:"password",
                typeName:"password",
            }
        },
        buttonTitle:"ログイン！！！",
        gobackBotton:"ホームに戻る",
        notingAcount:"ユーザ登録されていません",
        differentPassword:"パスワードが違います。",
        alertMessage:"ユーザ登録がされていない、もしくはパスワードが違います。もう一度確認して見てください。"
    },
    todo:{
        title:"TODO APP",
        description:"自分だけのTODOを作成しよう！",
        greeting:" Hello!!!!!",
        notLogin:"ログインしてから来いやー",
        buttonTitle:"登録",
        attribute:{
            todo:{
                labelName:"todo",
            },
        },
        logingMsg:"Loding...",
        complete:"完了タスク",
        imcomplete:"未完了タスク",
        notItem:"アイテムはありません",
        numOfPieces:"個"
    }
}